config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "index", to: "static_pages#index"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text"><%= t ".blog" %></h5>
        <p class="grey-text text-lighten-4"><%= t ".welcome" %></p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text"><%= t ".social" %></h5>
        <ul>
          <li><%= link_to t(".fb"), "https://facebook.com", class: "grey-text text-lighten-3" %></li>
          <li><%= link_to t(".ins"), "https://instagram.com", class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <%= t ".copyright" %>
      <%= link_to t(".ngoctuan"), "https://google.com", class: "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper light-blue">
    <%= link_to t(".home"), root_path, class: "brand-logo center" %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to t(".help"), help_path %></li>
      <li><%= link_to t(".about"), about_path %></li>
      <% if logged_in? %>
        <li><%= link_to t(".users"), users_path %></li>
        <ul id="dropdown1" class="dropdown-content">
          <li><%= link_to t(".profile"), current_user %></li>
          <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to t(".log_out"), logout_path, method: :delete %></li>
        </ul>
        <li>
          <a class="dropdown-button" href="#" data-activates="dropdown1">
          <%= t ".account" %>
          <i class="material-icons right">arrow_drop_down</i></a>
        </li>
      <% else %>
        <li><%= link_to t(".log_in"), login_path %></li>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <link rel="icon" href="blog-icon.png" size"32x32">
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |color, message| %>
        <div id="card-alert" class="card <%= color %>">
          <div class="card-content white-text">
            <%= message %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>